cookie:
  expiry_days: 15
  key: shop_floor
  name: users_cookie
credentials:
  usernames:
    ademir.nascimento@santamassa.com.br:
      email: ademir.nascimento@santamassa.com.br
      failed_login_attempts: 0
      logged_in: false
      name: Ademir Nascimento
      password: $2b$12$c4U5UbcZDJO5AlxKry5.7O/aYmXpQ224FyFdIt5rPsMxCRKc6syeu
      role: coordenador-pcp
    alexandre.diniz@santamassa.com.br:
      email: alexandre.diniz@santamassa.com.br
      failed_login_attempts: 0
      logged_in: false
      name: Alexandre Diniz
      password: $2b$12$jUwy4sMIvZDbIW2Bn2W59u0TXOub0K9/tj9RLngA2FKkN4FbR1Kgq
      role: coordenador
    bruno.tomaz@santamassa.com.br:
      email: bruno.tomaz@santamassa.com.br
      failed_login_attempts: 0
      logged_in: true
      name: Bruno Tomaz
      password: $2b$12$lVqbvhHuppk.FdFBSzQYoOwem2xcETu5pHRPWkAfk2TpDmNe15VOG
      role: dev
    cid.franciscon@santamassa.com.br:
      email: cid.franciscon@santamassa.com.br
      failed_login_attempts: 0
      logged_in: false
      name: Cid Franciscon
      password: $2b$12$0AzUoV4TlZBfZdJQtOg2QejaoTDRjEMgM1PU0Cw04EtY2XspQ/O8q
      role: coordenador
    guilherme.bandeira@santamassa.com.br:
      email: guilherme.bandeira@santamassa.com.br
      failed_login_attempts: 0
      logged_in: false
      name: Guilherme Bandeira
      password: $2b$12$9oqwEkpUT3amYorI/NdJI.//SkAI5tcPd4WpgqZDPfaTjphOqgK56
      role: gerente
pre-authorized:
  emails:
  - bruno.tomaz@santamassa.com.br
